-- palettes.lua — Master theme lookup table
-- Every theme-aware file reads from here instead of hardcoding colors.
-- Usage: local p = require("config.palettes")[require("config.theme").get()]

local M = {}

-- Theme cycle order
M.cycle = { "kanagawa", "catppuccin" }

-- ══════════════════════════════════════════════════════════════════
-- KANAGAWA — Japanese woodblock palette
-- Hokusai's Great Wave: ink, parchment, distant waves, autumn leaves
-- crystalBlue for the wave, oniViolet for the lotus, springGreen for bamboo
-- ══════════════════════════════════════════════════════════════════

M.kanagawa = {
  colorscheme = "cyberdream",
  border_style = "rounded",

  -- Reference palette — Kanagawa.nvim authentic colors
  colors = {
    bg = "#1F1F28",        -- sumiInk1  (deep ink, main bg)
    bg_alt = "#16161D",    -- sumiInk0  (deepest, tab bar bg)
    surface = "#2A2A37",   -- sumiInk2  (panels, floats)
    border = "#54546D",    -- sumiInk4  (borders, dividers)
    fg = "#DCD7BA",        -- fujiWhite (parchment text)
    fg_dim = "#C8C093",    -- oldWhite  (aged parchment)
    muted = "#727169",     -- fujiGray  (ink fading)
    accent = "#7E9CD8",    -- crystalBlue (the Great Wave)
    accent2 = "#957FB8",   -- oniViolet   (the lotus)
    green = "#98BB6C",     -- springGreen (bamboo)
    red = "#C34043",       -- autumnRed
    yellow = "#C0A36E",    -- carpYellow  (autumn carp)
    purple = "#938AA9",    -- springViolet
  },

  -- Heatmap gradient: L1 (faint) → L4 (full accent), deep-sea wave family
  heat_colors = { "#162840", "#254A70", "#4A78A8", "#7E9CD8" },

  guicursor = "n-v-c-sm:block-Cursor/lCursor,i-ci-ve:ver25-CursorInsert/lCursor,r-cr:hor20-CursorReplace/lCursor,o:hor50",
  cursor_highlights = {
    Cursor        = { fg = "#1F1F28", bg = "#7E9CD8" },   -- crystalBlue wave
    CursorInsert  = { fg = "#1F1F28", bg = "#98BB6C" },   -- springGreen bamboo
    CursorVisual  = { fg = "#DCD7BA", bg = "#957FB8" },   -- oniViolet lotus
    CursorReplace = { fg = "#1F1F28", bg = "#D27E99" },   -- sakuraPink cherry
  },

  fillchars = { eob = " ", fold = " ", foldopen = "▾", foldclose = "▸", foldsep = "│", vert = "│" },
  statuscolumn = "%s%=%{v:relnum?v:relnum:v:lnum} %C│",
  foldcolumn = "1",

  lualine_theme = {
    normal = {
      a = { fg = "#1F1F28", bg = "#7E9CD8", gui = "bold" },
      b = { fg = "#7E9CD8", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    insert = {
      a = { fg = "#1F1F28", bg = "#98BB6C", gui = "bold" },
      b = { fg = "#98BB6C", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    visual = {
      a = { fg = "#DCD7BA", bg = "#957FB8", gui = "bold" },
      b = { fg = "#957FB8", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    replace = {
      a = { fg = "#DCD7BA", bg = "#D27E99", gui = "bold" },
      b = { fg = "#D27E99", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    command = {
      a = { fg = "#1F1F28", bg = "#C0A36E", gui = "bold" },
      b = { fg = "#C0A36E", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    terminal = {
      a = { fg = "#1F1F28", bg = "#7AA89F", gui = "bold" },
      b = { fg = "#7AA89F", bg = "#2A2A37" },
      c = { fg = "#727169", bg = "#1a1a20" },
    },
    inactive = {
      a = { fg = "#727169", bg = "#1a1a20" },
      b = { fg = "#727169", bg = "#1a1a20" },
      c = { fg = "#54546D", bg = "#1a1a20" },
    },
  },
  lualine_component_sep = { left = "·", right = "·" },
  lualine_section_sep = { left = "", right = "" },
  lualine_mode_map = {
    ["NORMAL"]   = "UKIYO",
    ["INSERT"]   = "INKBRUSH",
    ["VISUAL"]   = "HAIKU",
    ["V-LINE"]   = "SCROLL",
    ["V-BLOCK"]  = "WOODBLOCK",
    ["COMMAND"]  = "SHOGUN",
    ["REPLACE"]  = "REWRITE",
    ["TERMINAL"] = "RONIN",
    ["SELECT"]   = "SELECT",
    ["EX"]       = "VOID",
  },
  lualine_macro_color = { fg = "#C34043" },
  lualine_lsp_color = { fg = "#7E9CD8" },

  dashboard_header = {
    "",
    "≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋",
    "██╗  ██╗ █████╗ ███╗  ██╗ █████╗ ",
    "██║ ██╔╝██╔══██╗████╗ ██║██╔══██╗",
    "█████╔╝ ███████║██╔██╗██║███████║",
    "██╔═██╗ ██╔══██║██║╚████║██╔══██║",
    "██║  ██╗██║  ██║██║ ╚███║██║  ██║",
    "╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚══╝╚═╝  ╚═╝",
    " ██████╗  █████╗ ██╗    ██╗ █████╗ ",
    "██╔════╝ ██╔══██╗██║    ██║██╔══██╗",
    "██║  ███╗███████║██║ █╗ ██║███████║",
    "██║   ██║██╔══██║██║███╗██║██╔══██║",
    "╚██████╔╝██║  ██║╚███╔███╔╝██║  ██║",
    " ╚═════╝ ╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝",
    "≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋≋",
    "    woodblock  ·  ink  ·  wave",
    "",
  },
  dashboard_icon_hl = "DashboardKanagawa",
  dashboard_footer_label = "≋ KANAGAWA",
  dashboard_gradient = {
    colors = { "DashboardKanagawa1", "DashboardKanagawa3" },
    smooth = true,
    ease = 0.72,
    tagline_hl = "DashboardKanagawa3",
    tagline_pattern = "woodblock",
  },

  telescope_layout = "horizontal",
  telescope_prompt_prefix = "   ",
  telescope_selection_caret = "  ",
  telescope_borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },

  noice_icons = {
    cmdline = " ≋",
    search_down = " /",
    search_up = " ?",
    filter = " $",
    lua = " ",
    help = " ?",
  },

  satellite_enabled = true,
  dropbar_enabled = true,
  dropbar_separator = " · ",
  indent_char = "│",
  notify_bg = "#1F1F28",

  highlights = {
    FloatBorder   = { fg = "#54546D", bg = "#1F1F28" },
    NormalFloat   = { bg = "#1F1F28" },
    WinSeparator  = { fg = "#2A2A37" },
    CursorLine    = { bg = "#25253a" },
    CursorLineNr  = { fg = "#7E9CD8", bold = true },
    LineNr        = { fg = "#363646" },
    Visual        = { bg = "#2D4F67" },
    Pmenu         = { bg = "#1F1F28", fg = "#727169" },
    PmenuSel      = { bg = "#2A2A37", fg = "#DCD7BA" },
    PmenuSbar     = { bg = "#16161D" },
    PmenuThumb    = { bg = "#7E9CD8" },
    Search        = { bg = "#2A2A37", fg = "#7E9CD8" },
    IncSearch     = { bg = "#7E9CD8", fg = "#1F1F28" },
    CurSearch     = { bg = "#C0A36E", fg = "#1F1F28" },
    DiagnosticError = { fg = "#C34043" },
    DiagnosticWarn  = { fg = "#C0A36E" },
    DiagnosticInfo  = { fg = "#7E9CD8" },
    DiagnosticHint  = { fg = "#727169" },
    GitSignsAdd    = { fg = "#98BB6C" },
    GitSignsChange = { fg = "#7E9CD8" },
    GitSignsDelete = { fg = "#C34043" },
    DashboardHeader    = { fg = "#7E9CD8" },
    DashboardCenter    = { fg = "#727169" },
    DashboardFooter    = { fg = "#54546D", italic = true },
    DashboardKanagawa  = { fg = "#7E9CD8" },
    DashboardKanagawa1 = { fg = "#7E9CD8" },
    DashboardKanagawa2 = { fg = "#7FB4CA" },
    DashboardKanagawa3 = { fg = "#C8C093" },
    IblIndent = { fg = "#25253a" },
    IblScope  = { fg = "#2d4060" },
    WhichKey      = { fg = "#7E9CD8" },
    WhichKeyGroup = { fg = "#957FB8" },
    WhichKeyDesc  = { fg = "#727169" },
    TelescopeBorder       = { fg = "#54546D" },
    TelescopePromptBorder = { fg = "#7E9CD8" },
    TelescopePromptTitle  = { fg = "#7E9CD8", bold = true },
    TelescopeResultsTitle = { fg = "#727169" },
    TelescopePreviewTitle = { fg = "#957FB8" },
    TelescopeSelection    = { bg = "#2A2A37" },
    NoiceCmdlinePopupBorder       = { fg = "#54546D" },
    NoiceCmdlinePopupTitle        = { fg = "#7E9CD8" },
    NoiceCmdlineIcon              = { fg = "#7E9CD8" },
    NoiceCmdlinePopupBorderSearch = { fg = "#957FB8" },
    NoiceConfirmBorder            = { fg = "#7E9CD8" },
    BufferLineIndicatorSelected = { fg = "#7E9CD8" },
    BufferLineFill              = { bg = "#16161D" },
    DropBarIconUISeparator    = { fg = "#54546D" },
    DropBarMenuCurrentContext = { bg = "#2A2A37" },
    SatelliteBar              = { bg = "#2A2A37" },
    SatelliteCursor           = { fg = "#7E9CD8" },
    FoldColumn      = { fg = "#363646" },
    Folded          = { bg = "#1F1F28", fg = "#727169" },
    StatusColumnSep = { fg = "#2A2A37" },
    NormalNC   = { bg = "#1c1c24" },
    Normal     = { bg = "#1F1F28", fg = "#DCD7BA" },
    Comment    = { fg = "#727169", italic = true },
    String     = { fg = "#98BB6C" },
    Keyword    = { fg = "#7E9CD8", bold = true },
    Function   = { fg = "#7FB4CA" },
    Type       = { fg = "#957FB8" },
    Identifier = { fg = "#DCD7BA" },
    Statement  = { fg = "#7E9CD8" },
    Constant   = { fg = "#D27E99" },
    Number     = { fg = "#FF9E3B" },
    Operator   = { fg = "#727169" },
    Special    = { fg = "#957FB8" },
    PreProc    = { fg = "#C0A36E" },
    Title      = { fg = "#7E9CD8", bold = true },
    ["@keyword"]     = { fg = "#7E9CD8", bold = true },
    ["@function"]    = { fg = "#7FB4CA" },
    ["@string"]      = { fg = "#98BB6C" },
    ["@type"]        = { fg = "#957FB8" },
    ["@variable"]    = { fg = "#DCD7BA" },
    ["@property"]    = { fg = "#C8C093" },
    ["@parameter"]   = { fg = "#DCD7BA" },
    ["@constructor"] = { fg = "#7E9CD8" },
    ["@punctuation"] = { fg = "#727169" },
    ["@comment"]     = { fg = "#727169", italic = true },
    ["@number"]      = { fg = "#FF9E3B" },
    ["@operator"]    = { fg = "#727169" },
    ["@constant"]    = { fg = "#D27E99" },
    FloatTitle     = { fg = "#7E9CD8", bold = true },
    FloatFooter    = { fg = "#54546D" },
    NonText        = { fg = "#54546D" },
    SpecialKey     = { fg = "#54546D" },
    EndOfBuffer    = { fg = "#16161D" },
    ModeMsg        = { fg = "#727169" },
    MoreMsg        = { fg = "#7E9CD8" },
    ErrorMsg       = { fg = "#C34043" },
    WarningMsg     = { fg = "#C0A36E" },
    PmenuKind      = { fg = "#7E9CD8", bg = "#1F1F28" },
    PmenuKindSel   = { fg = "#7E9CD8", bg = "#2A2A37" },
    PmenuExtra     = { fg = "#C8C093", bg = "#1F1F28" },
    PmenuExtraSel  = { fg = "#DCD7BA", bg = "#2A2A37" },
    LspSignatureActiveParameter = { fg = "#C0A36E", bold = true },
    LspInfoBorder               = { fg = "#54546D" },
    LspInlayHint                = { fg = "#54546D", italic = true, bg = "#1F1F28" },
    BlinkCmpMenu            = { bg = "#1F1F28", fg = "#DCD7BA" },
    BlinkCmpMenuBorder      = { fg = "#54546D" },
    BlinkCmpMenuSelection   = { bg = "#2A2A37" },
    BlinkCmpScrollBarGutter = { bg = "#16161D" },
    BlinkCmpScrollBarThumb  = { bg = "#54546D" },
    BlinkCmpLabel           = { fg = "#DCD7BA" },
    BlinkCmpLabelDeprecated = { fg = "#727169", strikethrough = true },
    BlinkCmpLabelMatch      = { fg = "#7E9CD8", bold = true },
    BlinkCmpLabelDetail     = { fg = "#C8C093" },
    BlinkCmpLabelDescription = { fg = "#727169" },
    BlinkCmpSource          = { fg = "#54546D" },
    BlinkCmpGhostText       = { fg = "#54546D", italic = true },
    BlinkCmpDoc             = { bg = "#1F1F28", fg = "#DCD7BA" },
    BlinkCmpDocBorder       = { fg = "#54546D" },
    BlinkCmpDocSeparator    = { fg = "#2A2A37" },
    BlinkCmpDocCursorLine   = { bg = "#2A2A37" },
    BlinkCmpSignatureHelp                = { bg = "#1F1F28", fg = "#DCD7BA" },
    BlinkCmpSignatureHelpBorder          = { fg = "#54546D" },
    BlinkCmpSignatureHelpActiveParameter = { fg = "#C0A36E", bold = true },
    BlinkCmpKind              = { fg = "#727169" },
    BlinkCmpKindText          = { fg = "#C8C093" },
    BlinkCmpKindMethod        = { fg = "#7FB4CA" },
    BlinkCmpKindFunction      = { fg = "#7FB4CA" },
    BlinkCmpKindConstructor   = { fg = "#7E9CD8" },
    BlinkCmpKindField         = { fg = "#DCD7BA" },
    BlinkCmpKindVariable      = { fg = "#DCD7BA" },
    BlinkCmpKindClass         = { fg = "#957FB8" },
    BlinkCmpKindInterface     = { fg = "#957FB8" },
    BlinkCmpKindModule        = { fg = "#7E9CD8" },
    BlinkCmpKindProperty      = { fg = "#C8C093" },
    BlinkCmpKindUnit          = { fg = "#D27E99" },
    BlinkCmpKindValue         = { fg = "#FF9E3B" },
    BlinkCmpKindEnum          = { fg = "#957FB8" },
    BlinkCmpKindKeyword       = { fg = "#7E9CD8" },
    BlinkCmpKindSnippet       = { fg = "#98BB6C" },
    BlinkCmpKindColor         = { fg = "#D27E99" },
    BlinkCmpKindFile          = { fg = "#C8C093" },
    BlinkCmpKindReference     = { fg = "#7E9CD8" },
    BlinkCmpKindFolder        = { fg = "#C8C093" },
    BlinkCmpKindEnumMember    = { fg = "#FF9E3B" },
    BlinkCmpKindConstant      = { fg = "#D27E99" },
    BlinkCmpKindStruct        = { fg = "#957FB8" },
    BlinkCmpKindEvent         = { fg = "#C0A36E" },
    BlinkCmpKindOperator      = { fg = "#727169" },
    BlinkCmpKindTypeParameter = { fg = "#957FB8" },
    DiffAdd    = { bg = "#1e2d1e" },
    DiffChange = { bg = "#1e1e2d" },
    DiffDelete = { bg = "#2d1e1e" },
    DiffText   = { bg = "#2D4F67" },
    DiffviewNormal             = { bg = "#16161D", fg = "#DCD7BA" },
    DiffviewNormalNC           = { bg = "#16161D", fg = "#727169" },
    DiffviewWinSeparator       = { fg = "#2A2A37" },
    DiffviewFilePanelTitle     = { fg = "#7E9CD8", bold = true },
    DiffviewFilePanelRootPath  = { fg = "#727169" },
    DiffviewFilePanelFileName  = { fg = "#DCD7BA" },
    DiffviewFilePanelCounter   = { fg = "#C0A36E" },
    DiffviewFilePanelConflicts = { fg = "#C34043" },
    DiffviewFolderSign         = { fg = "#7E9CD8" },
    DiffviewStatusAdded        = { fg = "#98BB6C" },
    DiffviewStatusModified     = { fg = "#7E9CD8" },
    DiffviewStatusDeleted      = { fg = "#C34043" },
    DiffviewStatusRenamed      = { fg = "#C0A36E" },
    DiffviewStatusUntracked    = { fg = "#727169" },
    TroubleNormal    = { bg = "#1F1F28", fg = "#DCD7BA" },
    TroubleNormalNC  = { bg = "#1F1F28", fg = "#727169" },
    TroubleCount     = { fg = "#7E9CD8", bold = true },
    TroubleCode      = { fg = "#727169" },
    TroubleSource    = { fg = "#54546D" },
    TroublePos       = { fg = "#54546D" },
    TroubleIndent    = { fg = "#363646" },
    TroubleIconError = { fg = "#C34043" },
    TroubleIconWarn  = { fg = "#C0A36E" },
    TroubleIconInfo  = { fg = "#7E9CD8" },
    TroubleIconHint  = { fg = "#727169" },
    NoiceFormatTitle  = { fg = "#7E9CD8", bold = true },
    NoiceFormatEvent  = { fg = "#727169", italic = true },
    NoiceVirtualText  = { fg = "#727169" },
  },

  terminal_colors = {
    [0]  = "#16161D",  [1]  = "#C34043",  [2]  = "#76946A",  [3]  = "#C0A36E",
    [4]  = "#7E9CD8",  [5]  = "#957FB8",  [6]  = "#6A9589",  [7]  = "#C8C093",
    [8]  = "#727169",  [9]  = "#E82424",  [10] = "#98BB6C",  [11] = "#E6C384",
    [12] = "#7FB4CA",  [13] = "#938AA9",  [14] = "#7AA89F",  [15] = "#DCD7BA",
  },

  cyberdream_colors = {
    bg           = "#1F1F28",
    bg_alt       = "#16161D",
    bg_highlight = "#2A2A37",
    fg           = "#DCD7BA",
    grey         = "#727169",
    blue         = "#7E9CD8",
    green        = "#98BB6C",
    cyan         = "#7AA89F",
    red          = "#C34043",
    yellow       = "#C0A36E",
    magenta      = "#957FB8",
    pink         = "#D27E99",
    orange       = "#FF9E3B",
    purple       = "#938AA9",
  },
}

-- ══════════════════════════════════════════════════════════════════
-- CATPPUCCIN MACCHIATO — Clean, focused, professional
-- Soft pastels on deep navy. No visual flair, just great colors.
-- ══════════════════════════════════════════════════════════════════

M.catppuccin = {
  colorscheme = "catppuccin",
  border_style = "rounded",

  -- Catppuccin Macchiato authentic palette
  colors = {
    bg = "#24273a",        -- base
    bg_alt = "#1e2030",    -- mantle
    surface = "#363a4f",   -- surface0
    border = "#494d64",    -- surface1
    fg = "#cad3f5",        -- text
    fg_dim = "#b8c0e0",    -- subtext1
    muted = "#6e738d",     -- overlay0
    accent = "#8aadf4",    -- blue
    accent2 = "#c6a0f6",   -- mauve
    green = "#a6da95",     -- green
    red = "#ed8796",       -- red
    yellow = "#eed49f",    -- yellow
    purple = "#c6a0f6",    -- mauve
  },

  heat_colors = { "#1a1d2e", "#2e3a5e", "#4a6098", "#8aadf4" },

  guicursor = "n-v-c-sm:block-Cursor/lCursor,i-ci-ve:ver25-CursorInsert/lCursor,r-cr:hor20-CursorReplace/lCursor,o:hor50",
  cursor_highlights = {
    Cursor        = { fg = "#24273a", bg = "#8aadf4" },   -- blue
    CursorInsert  = { fg = "#24273a", bg = "#a6da95" },   -- green
    CursorVisual  = { fg = "#24273a", bg = "#c6a0f6" },   -- mauve
    CursorReplace = { fg = "#24273a", bg = "#ed8796" },   -- red
  },

  fillchars = { eob = " ", fold = " ", foldopen = "▾", foldclose = "▸", foldsep = "│", vert = "│" },
  statuscolumn = "%s%=%{v:relnum?v:relnum:v:lnum} %C│",
  foldcolumn = "1",

  lualine_theme = {
    normal = {
      a = { fg = "#24273a", bg = "#8aadf4", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    insert = {
      a = { fg = "#24273a", bg = "#a6da95", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    visual = {
      a = { fg = "#24273a", bg = "#c6a0f6", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    replace = {
      a = { fg = "#24273a", bg = "#ed8796", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    command = {
      a = { fg = "#24273a", bg = "#eed49f", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    terminal = {
      a = { fg = "#24273a", bg = "#8bd5ca", gui = "bold" },
      b = { fg = "#cad3f5", bg = "#363a4f" },
      c = { fg = "#6e738d", bg = "#1e2030" },
    },
    inactive = {
      a = { fg = "#6e738d", bg = "#1e2030" },
      b = { fg = "#6e738d", bg = "#1e2030" },
      c = { fg = "#494d64", bg = "#1e2030" },
    },
  },
  lualine_component_sep = { left = "", right = "" },
  lualine_section_sep = { left = "", right = "" },
  lualine_mode_map = nil,  -- use default mode names
  lualine_macro_color = { fg = "#ed8796" },
  lualine_lsp_color = { fg = "#8aadf4" },

  -- Clean, minimal dashboard — no background art
  dashboard_header = {
    "",
    "  ╭──────────────────────────────────────╮",
    "  │                                      │",
    "  │   neovim  ·  wezterm  ·  catppuccin  │",
    "  │   ─────────────────────────────────  │",
    "  │         macchiato  ·  focused        │",
    "  │                                      │",
    "  ╰──────────────────────────────────────╯",
    "",
  },
  dashboard_icon_hl = "DashboardCatppuccin",
  dashboard_footer_label = "catppuccin macchiato",
  dashboard_gradient = {
    colors = { "DashboardCatppuccin1", "DashboardCatppuccin2" },
    smooth = false,
    ease = nil,
    tagline_hl = "DashboardCatppuccin2",
    tagline_pattern = "macchiato",
  },

  telescope_layout = "horizontal",
  telescope_prompt_prefix = "   ",
  telescope_selection_caret = "  ",
  telescope_borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },

  noice_icons = {
    cmdline = "  ",
    search_down = " /",
    search_up = " ?",
    filter = " $",
    lua = " ",
    help = " ?",
  },

  satellite_enabled = true,
  dropbar_enabled = true,
  dropbar_separator = " / ",
  indent_char = "│",
  notify_bg = "#24273a",

  highlights = {
    FloatBorder   = { fg = "#494d64", bg = "#24273a" },
    NormalFloat   = { bg = "#24273a" },
    WinSeparator  = { fg = "#363a4f" },
    CursorLine    = { bg = "#2a2d3e" },
    CursorLineNr  = { fg = "#8aadf4", bold = true },
    LineNr        = { fg = "#3a3d52" },
    Visual        = { bg = "#3a4060" },
    Pmenu         = { bg = "#1e2030", fg = "#6e738d" },
    PmenuSel      = { bg = "#363a4f", fg = "#cad3f5" },
    PmenuSbar     = { bg = "#1e2030" },
    PmenuThumb    = { bg = "#8aadf4" },
    Search        = { bg = "#363a4f", fg = "#8aadf4" },
    IncSearch     = { bg = "#8aadf4", fg = "#24273a" },
    CurSearch     = { bg = "#eed49f", fg = "#24273a" },
    DiagnosticError = { fg = "#ed8796" },
    DiagnosticWarn  = { fg = "#eed49f" },
    DiagnosticInfo  = { fg = "#8aadf4" },
    DiagnosticHint  = { fg = "#6e738d" },
    GitSignsAdd    = { fg = "#a6da95" },
    GitSignsChange = { fg = "#8aadf4" },
    GitSignsDelete = { fg = "#ed8796" },
    DashboardHeader       = { fg = "#8aadf4" },
    DashboardCenter       = { fg = "#6e738d" },
    DashboardFooter       = { fg = "#494d64", italic = true },
    DashboardCatppuccin   = { fg = "#8aadf4" },
    DashboardCatppuccin1  = { fg = "#8aadf4" },
    DashboardCatppuccin2  = { fg = "#c6a0f6" },
    IblIndent = { fg = "#2a2d3e" },
    IblScope  = { fg = "#363a4f" },
    WhichKey      = { fg = "#8aadf4" },
    WhichKeyGroup = { fg = "#c6a0f6" },
    WhichKeyDesc  = { fg = "#6e738d" },
    TelescopeBorder       = { fg = "#494d64" },
    TelescopePromptBorder = { fg = "#8aadf4" },
    TelescopePromptTitle  = { fg = "#8aadf4", bold = true },
    TelescopeResultsTitle = { fg = "#6e738d" },
    TelescopePreviewTitle = { fg = "#c6a0f6" },
    TelescopeSelection    = { bg = "#363a4f" },
    NoiceCmdlinePopupBorder       = { fg = "#494d64" },
    NoiceCmdlinePopupTitle        = { fg = "#8aadf4" },
    NoiceCmdlineIcon              = { fg = "#8aadf4" },
    NoiceCmdlinePopupBorderSearch = { fg = "#c6a0f6" },
    NoiceConfirmBorder            = { fg = "#8aadf4" },
    BufferLineIndicatorSelected = { fg = "#8aadf4" },
    BufferLineFill              = { bg = "#1e2030" },
    DropBarIconUISeparator    = { fg = "#494d64" },
    DropBarMenuCurrentContext = { bg = "#363a4f" },
    SatelliteBar              = { bg = "#363a4f" },
    SatelliteCursor           = { fg = "#8aadf4" },
    FoldColumn      = { fg = "#3a3d52" },
    Folded          = { bg = "#24273a", fg = "#6e738d" },
    StatusColumnSep = { fg = "#363a4f" },
    NormalNC        = { bg = "#20233a" },
    FloatTitle      = { fg = "#8aadf4", bold = true },
    FloatFooter     = { fg = "#494d64" },
    NonText         = { fg = "#494d64" },
    SpecialKey      = { fg = "#494d64" },
    EndOfBuffer     = { fg = "#1e2030" },
    ModeMsg         = { fg = "#6e738d" },
    MoreMsg         = { fg = "#8aadf4" },
    ErrorMsg        = { fg = "#ed8796" },
    WarningMsg      = { fg = "#eed49f" },
    LspSignatureActiveParameter = { fg = "#eed49f", bold = true },
    LspInfoBorder               = { fg = "#494d64" },
    LspInlayHint                = { fg = "#494d64", italic = true, bg = "#24273a" },
    BlinkCmpMenu            = { bg = "#1e2030", fg = "#cad3f5" },
    BlinkCmpMenuBorder      = { fg = "#494d64" },
    BlinkCmpMenuSelection   = { bg = "#363a4f" },
    BlinkCmpScrollBarGutter = { bg = "#1e2030" },
    BlinkCmpScrollBarThumb  = { bg = "#494d64" },
    BlinkCmpLabel           = { fg = "#cad3f5" },
    BlinkCmpLabelDeprecated = { fg = "#6e738d", strikethrough = true },
    BlinkCmpLabelMatch      = { fg = "#8aadf4", bold = true },
    BlinkCmpLabelDetail     = { fg = "#b8c0e0" },
    BlinkCmpLabelDescription = { fg = "#6e738d" },
    BlinkCmpSource          = { fg = "#494d64" },
    BlinkCmpGhostText       = { fg = "#494d64", italic = true },
    BlinkCmpDoc             = { bg = "#1e2030", fg = "#cad3f5" },
    BlinkCmpDocBorder       = { fg = "#494d64" },
    BlinkCmpDocSeparator    = { fg = "#363a4f" },
    BlinkCmpDocCursorLine   = { bg = "#363a4f" },
    BlinkCmpSignatureHelp                = { bg = "#1e2030", fg = "#cad3f5" },
    BlinkCmpSignatureHelpBorder          = { fg = "#494d64" },
    BlinkCmpSignatureHelpActiveParameter = { fg = "#eed49f", bold = true },
    BlinkCmpKind              = { fg = "#6e738d" },
    BlinkCmpKindText          = { fg = "#b8c0e0" },
    BlinkCmpKindMethod        = { fg = "#7dc4e4" },
    BlinkCmpKindFunction      = { fg = "#7dc4e4" },
    BlinkCmpKindConstructor   = { fg = "#8aadf4" },
    BlinkCmpKindField         = { fg = "#cad3f5" },
    BlinkCmpKindVariable      = { fg = "#cad3f5" },
    BlinkCmpKindClass         = { fg = "#c6a0f6" },
    BlinkCmpKindInterface     = { fg = "#c6a0f6" },
    BlinkCmpKindModule        = { fg = "#8aadf4" },
    BlinkCmpKindProperty      = { fg = "#b8c0e0" },
    BlinkCmpKindUnit          = { fg = "#f5bde6" },
    BlinkCmpKindValue         = { fg = "#f5a97f" },
    BlinkCmpKindEnum          = { fg = "#c6a0f6" },
    BlinkCmpKindKeyword       = { fg = "#8aadf4" },
    BlinkCmpKindSnippet       = { fg = "#a6da95" },
    BlinkCmpKindColor         = { fg = "#f5bde6" },
    BlinkCmpKindFile          = { fg = "#b8c0e0" },
    BlinkCmpKindReference     = { fg = "#8aadf4" },
    BlinkCmpKindFolder        = { fg = "#b8c0e0" },
    BlinkCmpKindEnumMember    = { fg = "#f5a97f" },
    BlinkCmpKindConstant      = { fg = "#f5bde6" },
    BlinkCmpKindStruct        = { fg = "#c6a0f6" },
    BlinkCmpKindEvent         = { fg = "#eed49f" },
    BlinkCmpKindOperator      = { fg = "#6e738d" },
    BlinkCmpKindTypeParameter = { fg = "#c6a0f6" },
    DiffAdd    = { bg = "#1e2d20" },
    DiffChange = { bg = "#1e2035" },
    DiffDelete = { bg = "#2d1e24" },
    DiffText   = { bg = "#3a4060" },
    DiffviewNormal             = { bg = "#1e2030", fg = "#cad3f5" },
    DiffviewNormalNC           = { bg = "#1e2030", fg = "#6e738d" },
    DiffviewWinSeparator       = { fg = "#363a4f" },
    DiffviewFilePanelTitle     = { fg = "#8aadf4", bold = true },
    DiffviewFilePanelRootPath  = { fg = "#6e738d" },
    DiffviewFilePanelFileName  = { fg = "#cad3f5" },
    DiffviewFilePanelCounter   = { fg = "#eed49f" },
    DiffviewFilePanelConflicts = { fg = "#ed8796" },
    DiffviewFolderSign         = { fg = "#8aadf4" },
    DiffviewStatusAdded        = { fg = "#a6da95" },
    DiffviewStatusModified     = { fg = "#8aadf4" },
    DiffviewStatusDeleted      = { fg = "#ed8796" },
    DiffviewStatusRenamed      = { fg = "#eed49f" },
    DiffviewStatusUntracked    = { fg = "#6e738d" },
    TroubleNormal    = { bg = "#24273a", fg = "#cad3f5" },
    TroubleNormalNC  = { bg = "#24273a", fg = "#6e738d" },
    TroubleCount     = { fg = "#8aadf4", bold = true },
    TroubleCode      = { fg = "#6e738d" },
    TroubleSource    = { fg = "#494d64" },
    TroublePos       = { fg = "#494d64" },
    TroubleIndent    = { fg = "#3a3d52" },
    TroubleIconError = { fg = "#ed8796" },
    TroubleIconWarn  = { fg = "#eed49f" },
    TroubleIconInfo  = { fg = "#8aadf4" },
    TroubleIconHint  = { fg = "#6e738d" },
    NoiceFormatTitle  = { fg = "#8aadf4", bold = true },
    NoiceFormatEvent  = { fg = "#6e738d", italic = true },
    NoiceVirtualText  = { fg = "#6e738d" },
  },

  terminal_colors = {
    [0]  = "#24273a",  [1]  = "#ed8796",  [2]  = "#a6da95",  [3]  = "#eed49f",
    [4]  = "#8aadf4",  [5]  = "#c6a0f6",  [6]  = "#8bd5ca",  [7]  = "#cad3f5",
    [8]  = "#5b6078",  [9]  = "#ed8796",  [10] = "#a6da95",  [11] = "#eed49f",
    [12] = "#7dc4e4",  [13] = "#f5bde6",  [14] = "#91d7e3",  [15] = "#b8c0e0",
  },
}

return M
